function pi_star = pluralityVoting(D)
%PLURALITYVOTING this function assigns data points to the cluster for which
% they hold the majority vote
%
%   PI_STAR = PLURALITYVOTING(D) returns the  BA of the consensus partition PI_STAR
%   which is generated by seeing to which cluster each data point has been
%   assigned the most, using the information from the voting matrix D. 
%

[N,K] = size(D);
pi_star = zeros(N, K);

for i=1:size(D,1)
    %Find the array index corresponding to  the value with the most occurrences
    [~,argmax]=max(D(i,:));
    %Assign point to cluster with more votes
    pi_star(i,argmax)=1;
end

end

