function pi_star = pluralityVoting(D)
%MAJORITYVOTING this function assigns data points to the cluster for which
% they hold the majority vote
%
%   PI_STAR = majorityVoting(D) returns the consensus partition PI_STAR
%   which is generated by seeing to which cluster each data point has been
%   assigned the most, using the information from the voting matrix D. 
%

pi_star = zeros(size(D,1), size(D,2));

for i=1:size(D,1)
    %Find the array index corresponding to  the value with the most occurrences
    [~,argmax]=max(D(i,:));
    %Assign point to cluster with more votes
    pi_star(i,argmax)=1;
end

end

